version: '2'
services:

  www:
    build: www/.
    ports:
      - "8001:80"
    links:
      - db
    depends_on:
      - db

  db:
    build: db/.
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: supersecure
       MYSQL_DATABASE: patient_sass
