version: '2'
services:
  www-base:
    build: www-base/.
    container_name: www-base
  www:
    build:
      context: www/.

    ports:
      - "80:80"
    links:
      - db
    depends_on:
      - db
    env_file: db.conf

  db:
    build: db/.
    volumes:
      - /var/lib/mysql
    env_file: db.conf
